# Generated by Django 5.2 on 2025-04-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/300x200', max_length=500),
        ),
    ]
